/**
 * Generates public/firebase-messaging-sw.js from .env variables.
 * Run automatically before dev/build via "predev" / "prebuild" npm scripts.
 */

const fs = require('fs');
const path = require('path');

// Load .env without external dependencies
function loadEnv() {
  const envPath = path.join(__dirname, '..', '.env');
  if (!fs.existsSync(envPath)) {
    console.warn('[build-sw] No .env file found. SW will use empty placeholders.');
    return {};
  }
  const lines = fs.readFileSync(envPath, 'utf8').split('\n');
  const env = {};
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx < 0) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const val = trimmed.slice(eqIdx + 1).trim().replace(/^["']|["']$/g, '');
    env[key] = val;
  }
  return env;
}

const env = loadEnv();

const apiKey = env.VITE_FIREBASE_API_KEY || '';
const projectId = env.VITE_FIREBASE_PROJECT_ID || '';
const messagingSenderId = env.VITE_FIREBASE_MESSAGING_SENDER_ID || '';
const appId = env.VITE_FIREBASE_APP_ID || '';
const authDomain = env.VITE_FIREBASE_AUTH_DOMAIN || '';
const storageBucket = env.VITE_FIREBASE_STORAGE_BUCKET || '';

const swContent = `// Auto-generated by scripts/build-sw.js — do not edit manually.
importScripts("https://www.gstatic.com/firebasejs/10.13.0/firebase-app-compat.js");
importScripts("https://www.gstatic.com/firebasejs/10.13.0/firebase-messaging-compat.js");

firebase.initializeApp({
  apiKey: "${apiKey}",
  authDomain: "${authDomain}",
  projectId: "${projectId}",
  storageBucket: "${storageBucket}",
  messagingSenderId: "${messagingSenderId}",
  appId: "${appId}",
});

const messaging = firebase.messaging();

messaging.onBackgroundMessage(({ notification, data }) => {
  if (!notification) return;
  self.registration.showNotification(notification.title || "Notificación CRM", {
    body: notification.body || "",
    icon: "/logoIDG.jpg",
    badge: "/logoIDG.jpg",
    data: data || {},
  });
});

self.addEventListener("notificationclick", (event) => {
  event.notification.close();
  const link = event.notification.data?.link || "/";
  event.waitUntil(
    clients
      .matchAll({ type: "window", includeUncontrolled: true })
      .then((windowClients) => {
        for (const client of windowClients) {
          if (client.url.includes(self.location.origin) && "focus" in client) {
            client.navigate(link);
            return client.focus();
          }
        }
        return clients.openWindow(link);
      })
  );
});
`;

const publicDir = path.join(__dirname, '..', 'public');
if (!fs.existsSync(publicDir)) {
  fs.mkdirSync(publicDir, { recursive: true });
}

const outPath = path.join(publicDir, 'firebase-messaging-sw.js');
fs.writeFileSync(outPath, swContent, 'utf8');
console.log('[build-sw] Generated public/firebase-messaging-sw.js');
